project:
  type: website
  render:
    - win11-for-engineers-manual.qmd

website:
  navbar:
    right:
      - win11-for-engineers-manual.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true

execute:
  freeze: auto

