project:
  type: website
  render:
    - win11-for-engineers-manual.qmd

website:
  navbar:
    right:
      - win11-for-engineers-manual.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

#engines: ['julia', 'jupyter']
#engines: ['jupyter', 'julia']
#execute:
#  freeze: false
#  #freeze: auto
#  cache: false

